/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {

//  ----- Restaurants -----
        Restaurant pizza = new Restaurant("pizzatime", "$$$", 4);
        Restaurant chipotle = new Restaurant("chipotle", "$$", 5);


//  ----- Reviews -----
        Review pizzaReview = new Review("this pizza was terrible","chandler",1);
        Review pizzaReview2 = new Review("worst slice ever","dave",2);

        Review chipRev = new Review("love these burritos", "carl", 4);
        Review chipRev2 = new Review("hot fire", "cindy", 5);
        Review chipRev3 = new Review("bugs in my burrito bowl", "howard",1);


//  ----- link the review to the restaurant -----
        pizza.addReview(pizzaReview);
        pizza.addReview(pizzaReview2);

        chipotle.addReview(chipRev);
        chipotle.addReview(chipRev2);
        chipotle.addReview(chipRev3);

        System.out.println("PIZZA PLACE:");
        System.out.println(pizza);
        System.out.println(pizza.reviewList);
        System.out.println();

        System.out.println("CHIPOTLE:");
        System.out.println(chipotle);
        System.out.println(chipotle.reviewList);

    }
}
