/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library test = new Library();
        assertTrue("someLibraryMethod should return 'true'", test.someLibraryMethod());
    }

    @Test
    public void testWeatherData (){
        Library test = new Library();

        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        assertEquals(
                "the high temp is High: 71",
                test.analyzeWeatherData(weeklyMonthTemperatures),
                "High: 71"
                    );
    }
}
